name: rrat
dependencies:
- backports=1.0=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_0
- backports_abc=0.4=py27_0
- blas=1.1=openblas
- bokeh=0.12.0=py27_0
- boost=1.57.0=4
- casa-data=r10774=0
- casa-nrao-casacore=4.6.0=1
- casa-python=4.6.0=py27_2
- casa-tools=4.6.0=2
- cfitsio=3.370=2
- configparser=3.5.0b2=py27_1
- cycler=0.10.0=py27_0
- cython=0.24=py27_0
- dbus-client=1.10.6=0
- dbus-cxx=0.9.0=0
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- expat=2.1.0=1
- fftw=3.3.4=3
- fontconfig=2.11.1=3
- freetype=2.6.3=1
- functools32=3.2.3.2=py27_1
- futures=3.0.5=py27_0
- gettext=0.19.7=1
- glib=2.48.0=4
- gsl=2.1=1
- hdf5=1.8.17=2
- icu=56.1=4
- ipykernel=4.3.1=py27_0
- ipython=5.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.1.5=py27_0
- jinja2=2.8=py27_1
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.3.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.1.0=py27_0
- libffi=3.2.1=2
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=2
- libpng=1.6.23=0
- libsakura=2.0.0=0
- libsodium=1.0.10=0
- libxml2=2.9.3=8
- libxslt=1.1.28=0
- markupsafe=0.23=py27_2
- matplotlib=1.5.2=np111py27_5
- mistune=0.7.3=py27_0
- modern-xorg-stack=2016.03=0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- ncurses=5.9=7
- notebook=4.2.1=py27_0
- numpy=1.11.1=py27_blas_openblas_200
- openblas=0.2.18=2
- openssl=1.0.2h=1
- path.py=8.2.1=py27_0
- pathlib=1.0.1=py27_1
- pathlib2=2.1.0=py27_0
- pcre=8.38=1
- pexpect=4.1.0=py27_0
- pgplot=5.2.2=8
- pickleshare=0.5=py27_0
- pip=8.1.2=py27_0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pwkit=0.8.4=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_3
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- pyyaml=3.11=py27_4
- pyzmq=15.2.0=py27_1
- qt=4.8.7=3
- qtconsole=4.2.1=py27_0
- qwt5=5.2.3=0
- readline=6.2=2
- requests=2.10.0=py27_0
- rpfits=2.23=5
- scipy=0.17.1=np111py27_blas_openblas_201
- setuptools=23.0.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_0
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_1
- traitlets=4.2.2=py27_0
- wcslib=5.12=2
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.3=py27_1
- xerces-c28=2.8.0=0
- xz=5.0.5=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - click==6.6
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - lxml==3.6.0
  - prompt-toolkit==1.0.3
  - pyfftw==0.10.4
  - rtpipe==1.46
  - sdmpy==1.35

